services:
  - type: web
    name: recommend-backend
    env: python
    buildCommand: chmod a+x start.sh && pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
